Polish Help Text
wshito/asciidoctor-chunker pull request #24
Opened 2021-10-31 04:35 UTC by tajmone

Fix typos and polish English of the text shown via `--help`.

2021-10-31 13:15 UTC, wshito commented
@tajmone Thank you for your contribution!  I will review it when I have time.  I am quite busy with my work at the moment so please give me some time.

2021-10-31 16:44 UTC, tajmone commented
Don't worry, it's nothing urgent, just aesthetic improvements.

2021-11-05 00:23 UTC, wshito requested changes
Thank you for your contribution.  I left comments where I prefer the original.

2021-11-05 00:23 UTC, wshito commented on src/CommandOptions.mjs
> +  You can specify the extraction level via the '--depth' option.
I prefer the original here.

2021-11-05 00:23 UTC, wshito commented on src/CommandOptions.mjs
> +  means chapter 1 through 5 should be extracted with the depth
I like to keep the original except the word `collon-separated` in the first line as you proposed.

2021-11-05 00:23 UTC, wshito commented on src/CommandOptions.mjs
> +  --depth 1,3-8:2    Set default level 1, and level 2 for Chs. 3 to 8.
Please change 'Set' to 'Sets' here.

2021-11-07 00:54 UTC, merged